package org.sat4j.tools;


import org.junit.Assert;
import org.junit.Test;
import org.sat4j.core.VecInt;
import org.sat4j.minisat.SolverFactory;
import org.sat4j.minisat.constraints.cnf.OriginalBinaryClause;
import org.sat4j.minisat.constraints.cnf.OriginalWLClause;
import org.sat4j.minisat.constraints.cnf.UnitClause;
import org.sat4j.specs.ContradictionException;
import org.sat4j.specs.IConstr;
import org.sat4j.specs.ISolver;
import org.sat4j.specs.IVecInt;
import org.sat4j.specs.TimeoutException;


public class BackboneTest {
    @Test(timeout = 10000)
    public void testEasyCaseWithOnlyOneModel() throws Exception, ContradictionException, TimeoutException {
        ISolver solver = SolverFactory.newDefault();
        IVecInt clause = new VecInt();
        IVecInt o_testEasyCaseWithOnlyOneModel__5 = clause.push(1).push(2).push(3);
        Assert.assertEquals("1,2,3", ((VecInt) (o_testEasyCaseWithOnlyOneModel__5)).toString());
        Assert.assertEquals(2, ((int) (((VecInt) (o_testEasyCaseWithOnlyOneModel__5)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testEasyCaseWithOnlyOneModel__5)).isEmpty());
        IConstr o_testEasyCaseWithOnlyOneModel__8 = solver.addClause(clause);
        Assert.assertFalse(((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).getActivity())), 0.1);
        int[] array_93386990 = new int[]{2,4,6};
        	int[] array_1694934693 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalWLClause)o_testEasyCaseWithOnlyOneModel__8).getLits();
        	for(int ii = 0; ii <array_93386990.length; ii++) {
        		org.junit.Assert.assertEquals(array_93386990[ii], array_1694934693[ii]);
        	};
        Assert.assertEquals("1[?] 2[?] 3[?] ", ((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).toString());
        Assert.assertEquals(4, ((int) (((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).hashCode())));
        clause.clear();
        IVecInt o_testEasyCaseWithOnlyOneModel__10 = clause.push((-1)).push((-2));
        Assert.assertEquals("-1,-2", ((VecInt) (o_testEasyCaseWithOnlyOneModel__10)).toString());
        Assert.assertEquals(-1, ((int) (((VecInt) (o_testEasyCaseWithOnlyOneModel__10)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testEasyCaseWithOnlyOneModel__10)).isEmpty());
        IConstr o_testEasyCaseWithOnlyOneModel__14 = solver.addClause(clause);
        Assert.assertFalse(((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).getActivity())), 0.1);
        int[] array_693168991 = new int[]{3,5};
        	int[] array_1819371744 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testEasyCaseWithOnlyOneModel__14).getLits();
        	for(int ii = 0; ii <array_693168991.length; ii++) {
        		org.junit.Assert.assertEquals(array_693168991[ii], array_1819371744[ii]);
        	};
        Assert.assertEquals("-1[?] -2[?]", ((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).toString());
        Assert.assertEquals(4, ((int) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).hashCode())));
        clause.clear();
        IVecInt o_testEasyCaseWithOnlyOneModel__16 = clause.push((-1)).push((-3));
        Assert.assertEquals("-1,-3", ((VecInt) (o_testEasyCaseWithOnlyOneModel__16)).toString());
        Assert.assertEquals(-2, ((int) (((VecInt) (o_testEasyCaseWithOnlyOneModel__16)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testEasyCaseWithOnlyOneModel__16)).isEmpty());
        IConstr o_testEasyCaseWithOnlyOneModel__20 = solver.addClause(clause);
        Assert.assertFalse(((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).getActivity())), 0.1);
        int[] array_133895881 = new int[]{3,7};
        	int[] array_704882353 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testEasyCaseWithOnlyOneModel__20).getLits();
        	for(int ii = 0; ii <array_133895881.length; ii++) {
        		org.junit.Assert.assertEquals(array_133895881[ii], array_704882353[ii]);
        	};
        Assert.assertEquals("-1[?] -3[?]", ((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).toString());
        Assert.assertEquals(5, ((int) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).hashCode())));
        clause.clear();
        IVecInt o_testEasyCaseWithOnlyOneModel__22 = clause.push(1);
        Assert.assertEquals("1", ((VecInt) (o_testEasyCaseWithOnlyOneModel__22)).toString());
        Assert.assertEquals(1, ((int) (((VecInt) (o_testEasyCaseWithOnlyOneModel__22)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testEasyCaseWithOnlyOneModel__22)).isEmpty());
        IConstr o_testEasyCaseWithOnlyOneModel__23 = solver.addClause(clause);
        Assert.assertTrue(((UnitClause) (o_testEasyCaseWithOnlyOneModel__23)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((UnitClause) (o_testEasyCaseWithOnlyOneModel__23)).getActivity())), 0.1);
        Assert.assertEquals("1", ((UnitClause) (o_testEasyCaseWithOnlyOneModel__23)).toString());
        clause.clear();
        IVecInt backbone = Backbone.instance().compute(solver);
        boolean o_testEasyCaseWithOnlyOneModel__28 = backbone.contains(1);
        Assert.assertTrue(o_testEasyCaseWithOnlyOneModel__28);
        boolean o_testEasyCaseWithOnlyOneModel__29 = backbone.contains((-2));
        Assert.assertTrue(o_testEasyCaseWithOnlyOneModel__29);
        boolean o_testEasyCaseWithOnlyOneModel__31 = backbone.contains((-3));
        Assert.assertTrue(o_testEasyCaseWithOnlyOneModel__31);
        Assert.assertEquals("", ((VecInt) (o_testEasyCaseWithOnlyOneModel__5)).toString());
        Assert.assertTrue(((VecInt) (o_testEasyCaseWithOnlyOneModel__5)).isEmpty());
        Assert.assertTrue(((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).getActivity())), 0.1);
        int[] array_2094448682 = new int[]{2,4,6};
        	int[] array_476261279 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalWLClause)o_testEasyCaseWithOnlyOneModel__8).getLits();
        	for(int ii = 0; ii <array_2094448682.length; ii++) {
        		org.junit.Assert.assertEquals(array_2094448682[ii], array_476261279[ii]);
        	};
        Assert.assertEquals("1[T] 2[?] 3[?] ", ((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).toString());
        Assert.assertEquals(4, ((int) (((OriginalWLClause) (o_testEasyCaseWithOnlyOneModel__8)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testEasyCaseWithOnlyOneModel__10)).toString());
        Assert.assertTrue(((VecInt) (o_testEasyCaseWithOnlyOneModel__10)).isEmpty());
        Assert.assertFalse(((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).getActivity())), 0.1);
        int[] array_1099665245 = new int[]{3,5};
        	int[] array_1020946551 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testEasyCaseWithOnlyOneModel__14).getLits();
        	for(int ii = 0; ii <array_1099665245.length; ii++) {
        		org.junit.Assert.assertEquals(array_1099665245[ii], array_1020946551[ii]);
        	};
        Assert.assertEquals("-1[F] -2[?]", ((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).toString());
        Assert.assertEquals(4, ((int) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__14)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testEasyCaseWithOnlyOneModel__16)).toString());
        Assert.assertTrue(((VecInt) (o_testEasyCaseWithOnlyOneModel__16)).isEmpty());
        Assert.assertFalse(((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).getActivity())), 0.1);
        int[] array_1495089740 = new int[]{3,7};
        	int[] array_1221105098 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testEasyCaseWithOnlyOneModel__20).getLits();
        	for(int ii = 0; ii <array_1495089740.length; ii++) {
        		org.junit.Assert.assertEquals(array_1495089740[ii], array_1221105098[ii]);
        	};
        Assert.assertEquals("-1[F] -3[?]", ((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).toString());
        Assert.assertEquals(5, ((int) (((OriginalBinaryClause) (o_testEasyCaseWithOnlyOneModel__20)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testEasyCaseWithOnlyOneModel__22)).toString());
        Assert.assertTrue(((VecInt) (o_testEasyCaseWithOnlyOneModel__22)).isEmpty());
        Assert.assertTrue(((UnitClause) (o_testEasyCaseWithOnlyOneModel__23)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((UnitClause) (o_testEasyCaseWithOnlyOneModel__23)).getActivity())), 0.1);
        Assert.assertEquals("1", ((UnitClause) (o_testEasyCaseWithOnlyOneModel__23)).toString());
        Assert.assertTrue(o_testEasyCaseWithOnlyOneModel__28);
        Assert.assertTrue(o_testEasyCaseWithOnlyOneModel__29);
    }

    @Test(timeout = 10000)
    public void testFilter() throws Exception, ContradictionException, TimeoutException {
        ISolver solver = SolverFactory.newDefault();
        IVecInt clause = new VecInt();
        IVecInt o_testFilter__5 = clause.push(1).push(2).push(3);
        Assert.assertEquals("1,2,3", ((VecInt) (o_testFilter__5)).toString());
        Assert.assertEquals(2, ((int) (((VecInt) (o_testFilter__5)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testFilter__5)).isEmpty());
        IConstr o_testFilter__8 = solver.addClause(clause);
        Assert.assertFalse(((OriginalWLClause) (o_testFilter__8)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalWLClause) (o_testFilter__8)).getActivity())), 0.1);
        int[] array_1775383297 = new int[]{2,4,6};
        	int[] array_1318706812 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalWLClause)o_testFilter__8).getLits();
        	for(int ii = 0; ii <array_1775383297.length; ii++) {
        		org.junit.Assert.assertEquals(array_1775383297[ii], array_1318706812[ii]);
        	};
        Assert.assertEquals("1[?] 2[?] 3[?] ", ((OriginalWLClause) (o_testFilter__8)).toString());
        Assert.assertEquals(4, ((int) (((OriginalWLClause) (o_testFilter__8)).hashCode())));
        clause.clear();
        IVecInt o_testFilter__10 = clause.push((-1)).push(2).push(3);
        Assert.assertEquals("-1,2,3", ((VecInt) (o_testFilter__10)).toString());
        Assert.assertEquals(1, ((int) (((VecInt) (o_testFilter__10)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testFilter__10)).isEmpty());
        IConstr o_testFilter__14 = solver.addClause(clause);
        Assert.assertFalse(((OriginalWLClause) (o_testFilter__14)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalWLClause) (o_testFilter__14)).getActivity())), 0.1);
        int[] array_823822799 = new int[]{3,4,6};
        	int[] array_2137733469 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalWLClause)o_testFilter__14).getLits();
        	for(int ii = 0; ii <array_823822799.length; ii++) {
        		org.junit.Assert.assertEquals(array_823822799[ii], array_2137733469[ii]);
        	};
        Assert.assertEquals("-1[?] 2[?] 3[?] ", ((OriginalWLClause) (o_testFilter__14)).toString());
        Assert.assertEquals(4, ((int) (((OriginalWLClause) (o_testFilter__14)).hashCode())));
        clause.clear();
        IVecInt o_testFilter__16 = clause.push(1).push((-2));
        Assert.assertEquals("1,-2", ((VecInt) (o_testFilter__16)).toString());
        Assert.assertEquals(0, ((int) (((VecInt) (o_testFilter__16)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testFilter__16)).isEmpty());
        IConstr o_testFilter__19 = solver.addClause(clause);
        Assert.assertFalse(((OriginalBinaryClause) (o_testFilter__19)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testFilter__19)).getActivity())), 0.1);
        int[] array_376272347 = new int[]{2,5};
        	int[] array_2013800860 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testFilter__19).getLits();
        	for(int ii = 0; ii <array_376272347.length; ii++) {
        		org.junit.Assert.assertEquals(array_376272347[ii], array_2013800860[ii]);
        	};
        Assert.assertEquals("1[?] -2[?]", ((OriginalBinaryClause) (o_testFilter__19)).toString());
        Assert.assertEquals(3, ((int) (((OriginalBinaryClause) (o_testFilter__19)).hashCode())));
        clause.clear();
        IVecInt o_testFilter__21 = clause.push((-1)).push((-2));
        Assert.assertEquals("-1,-2", ((VecInt) (o_testFilter__21)).toString());
        Assert.assertEquals(-1, ((int) (((VecInt) (o_testFilter__21)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testFilter__21)).isEmpty());
        IConstr o_testFilter__25 = solver.addClause(clause);
        Assert.assertFalse(((OriginalBinaryClause) (o_testFilter__25)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testFilter__25)).getActivity())), 0.1);
        int[] array_459256098 = new int[]{3,5};
        	int[] array_1110374170 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testFilter__25).getLits();
        	for(int ii = 0; ii <array_459256098.length; ii++) {
        		org.junit.Assert.assertEquals(array_459256098[ii], array_1110374170[ii]);
        	};
        Assert.assertEquals("-1[?] -2[?]", ((OriginalBinaryClause) (o_testFilter__25)).toString());
        Assert.assertEquals(4, ((int) (((OriginalBinaryClause) (o_testFilter__25)).hashCode())));
        clause.clear();
        IVecInt filter = new VecInt(new int[]{ 1, 2 });
        IVecInt backbone = Backbone.instance().compute(solver, VecInt.EMPTY, filter);
        int o_testFilter__32 = backbone.size();
        Assert.assertEquals(1, ((int) (o_testFilter__32)));
        boolean o_testFilter__33 = backbone.contains((-2));
        Assert.assertTrue(o_testFilter__33);
        boolean o_testFilter__35 = backbone.contains(3);
        Assert.assertFalse(o_testFilter__35);
        backbone = Backbone.instance().compute(solver);
        int o_testFilter__39 = backbone.size();
        Assert.assertEquals(2, ((int) (o_testFilter__39)));
        boolean o_testFilter__40 = backbone.contains((-2));
        Assert.assertTrue(o_testFilter__40);
        boolean o_testFilter__42 = backbone.contains((-2));
        Assert.assertTrue(o_testFilter__42);
        boolean o_testFilter__44 = backbone.contains(3);
        Assert.assertTrue(o_testFilter__44);
        Assert.assertEquals("", ((VecInt) (o_testFilter__5)).toString());
        Assert.assertTrue(((VecInt) (o_testFilter__5)).isEmpty());
        Assert.assertFalse(((OriginalWLClause) (o_testFilter__8)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalWLClause) (o_testFilter__8)).getActivity())), 0.1);
        int[] array_2035717878 = new int[]{4,2,6};
        	int[] array_2069531944 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalWLClause)o_testFilter__8).getLits();
        	for(int ii = 0; ii <array_2035717878.length; ii++) {
        		org.junit.Assert.assertEquals(array_2035717878[ii], array_2069531944[ii]);
        	};
        Assert.assertEquals("2[?] 1[?] 3[?] ", ((OriginalWLClause) (o_testFilter__8)).toString());
        Assert.assertEquals(4, ((int) (((OriginalWLClause) (o_testFilter__8)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testFilter__10)).toString());
        Assert.assertTrue(((VecInt) (o_testFilter__10)).isEmpty());
        Assert.assertFalse(((OriginalWLClause) (o_testFilter__14)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalWLClause) (o_testFilter__14)).getActivity())), 0.1);
        int[] array_1439016066 = new int[]{4,3,6};
        	int[] array_1867322158 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalWLClause)o_testFilter__14).getLits();
        	for(int ii = 0; ii <array_1439016066.length; ii++) {
        		org.junit.Assert.assertEquals(array_1439016066[ii], array_1867322158[ii]);
        	};
        Assert.assertEquals("2[?] -1[?] 3[?] ", ((OriginalWLClause) (o_testFilter__14)).toString());
        Assert.assertEquals(4, ((int) (((OriginalWLClause) (o_testFilter__14)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testFilter__16)).toString());
        Assert.assertTrue(((VecInt) (o_testFilter__16)).isEmpty());
        Assert.assertFalse(((OriginalBinaryClause) (o_testFilter__19)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testFilter__19)).getActivity())), 0.1);
        int[] array_2076912544 = new int[]{2,5};
        	int[] array_1469107799 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testFilter__19).getLits();
        	for(int ii = 0; ii <array_2076912544.length; ii++) {
        		org.junit.Assert.assertEquals(array_2076912544[ii], array_1469107799[ii]);
        	};
        Assert.assertEquals("1[?] -2[?]", ((OriginalBinaryClause) (o_testFilter__19)).toString());
        Assert.assertEquals(3, ((int) (((OriginalBinaryClause) (o_testFilter__19)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testFilter__21)).toString());
        Assert.assertTrue(((VecInt) (o_testFilter__21)).isEmpty());
        Assert.assertFalse(((OriginalBinaryClause) (o_testFilter__25)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testFilter__25)).getActivity())), 0.1);
        int[] array_1031401030 = new int[]{3,5};
        	int[] array_471243514 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testFilter__25).getLits();
        	for(int ii = 0; ii <array_1031401030.length; ii++) {
        		org.junit.Assert.assertEquals(array_1031401030[ii], array_471243514[ii]);
        	};
        Assert.assertEquals("-1[?] -2[?]", ((OriginalBinaryClause) (o_testFilter__25)).toString());
        Assert.assertEquals(4, ((int) (((OriginalBinaryClause) (o_testFilter__25)).hashCode())));
        Assert.assertEquals(1, ((int) (o_testFilter__32)));
        Assert.assertTrue(o_testFilter__33);
        Assert.assertFalse(o_testFilter__35);
        Assert.assertEquals(2, ((int) (o_testFilter__39)));
        Assert.assertTrue(o_testFilter__40);
        Assert.assertTrue(o_testFilter__42);
    }

    @Test(timeout = 10000)
    public void testBugBr4cp() throws Exception, ContradictionException, TimeoutException {
        ISolver solver = SolverFactory.newDefault();
        IVecInt clause = new VecInt();
        IVecInt o_testBugBr4cp__5 = clause.push(1);
        Assert.assertEquals("1", ((VecInt) (o_testBugBr4cp__5)).toString());
        Assert.assertEquals(1, ((int) (((VecInt) (o_testBugBr4cp__5)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testBugBr4cp__5)).isEmpty());
        IConstr o_testBugBr4cp__6 = solver.addClause(clause);
        Assert.assertTrue(((UnitClause) (o_testBugBr4cp__6)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((UnitClause) (o_testBugBr4cp__6)).getActivity())), 0.1);
        Assert.assertEquals("1", ((UnitClause) (o_testBugBr4cp__6)).toString());
        clause.clear();
        IVecInt o_testBugBr4cp__8 = clause.push(2).push(3);
        Assert.assertEquals("2,3", ((VecInt) (o_testBugBr4cp__8)).toString());
        Assert.assertEquals(2, ((int) (((VecInt) (o_testBugBr4cp__8)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testBugBr4cp__8)).isEmpty());
        IConstr o_testBugBr4cp__10 = solver.addClause(clause);
        Assert.assertFalse(((OriginalBinaryClause) (o_testBugBr4cp__10)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testBugBr4cp__10)).getActivity())), 0.1);
        int[] array_353699734 = new int[]{4,6};
        	int[] array_1690891046 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testBugBr4cp__10).getLits();
        	for(int ii = 0; ii <array_353699734.length; ii++) {
        		org.junit.Assert.assertEquals(array_353699734[ii], array_1690891046[ii]);
        	};
        Assert.assertEquals("2[?] 3[?]", ((OriginalBinaryClause) (o_testBugBr4cp__10)).toString());
        Assert.assertEquals(5, ((int) (((OriginalBinaryClause) (o_testBugBr4cp__10)).hashCode())));
        clause.clear();
        IVecInt o_testBugBr4cp__12 = clause.push((-2)).push((-3));
        Assert.assertEquals("-2,-3", ((VecInt) (o_testBugBr4cp__12)).toString());
        Assert.assertEquals(-2, ((int) (((VecInt) (o_testBugBr4cp__12)).hashCode())));
        Assert.assertFalse(((VecInt) (o_testBugBr4cp__12)).isEmpty());
        IConstr o_testBugBr4cp__16 = solver.addClause(clause);
        Assert.assertFalse(((OriginalBinaryClause) (o_testBugBr4cp__16)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testBugBr4cp__16)).getActivity())), 0.1);
        int[] array_780889173 = new int[]{5,7};
        	int[] array_617195729 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testBugBr4cp__16).getLits();
        	for(int ii = 0; ii <array_780889173.length; ii++) {
        		org.junit.Assert.assertEquals(array_780889173[ii], array_617195729[ii]);
        	};
        Assert.assertEquals("-2[?] -3[?]", ((OriginalBinaryClause) (o_testBugBr4cp__16)).toString());
        Assert.assertEquals(6, ((int) (((OriginalBinaryClause) (o_testBugBr4cp__16)).hashCode())));
        clause.clear();
        IVecInt backbone = Backbone.instance().compute(solver);
        int o_testBugBr4cp__21 = backbone.size();
        Assert.assertEquals(1, ((int) (o_testBugBr4cp__21)));
        int o_testBugBr4cp__22 = backbone.get(0);
        Assert.assertEquals(1, ((int) (o_testBugBr4cp__22)));
        boolean o_testBugBr4cp__23 = solver.isSatisfiable(new VecInt(new int[]{ 2 }));
        Assert.assertTrue(o_testBugBr4cp__23);
        boolean o_testBugBr4cp__25 = solver.isSatisfiable(new VecInt(new int[]{ 3 }));
        Assert.assertTrue(o_testBugBr4cp__25);
        boolean o_testBugBr4cp__27 = solver.isSatisfiable(new VecInt(new int[]{ -2 }));
        Assert.assertTrue(o_testBugBr4cp__27);
        boolean o_testBugBr4cp__30 = solver.isSatisfiable(new VecInt(new int[]{ -3 }));
        Assert.assertTrue(o_testBugBr4cp__30);
        backbone = Backbone.instance().compute(solver, new VecInt(new int[]{ 2 }));
        int o_testBugBr4cp__37 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__37)));
        backbone = Backbone.instance().compute(solver, new VecInt(new int[]{ -2 }));
        int o_testBugBr4cp__43 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__43)));
        int o_testBugBr4cp__44 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__44)));
        backbone = Backbone.instance().compute(solver, new VecInt(new int[]{ 3 }));
        int o_testBugBr4cp__49 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__49)));
        int o_testBugBr4cp__50 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__50)));
        int o_testBugBr4cp__51 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__51)));
        backbone = Backbone.instance().compute(solver, new VecInt(new int[]{ -3 }));
        int o_testBugBr4cp__57 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__57)));
        int o_testBugBr4cp__58 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__58)));
        int o_testBugBr4cp__59 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__59)));
        int o_testBugBr4cp__60 = backbone.size();
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__60)));
        Assert.assertEquals("", ((VecInt) (o_testBugBr4cp__5)).toString());
        Assert.assertTrue(((VecInt) (o_testBugBr4cp__5)).isEmpty());
        Assert.assertTrue(((UnitClause) (o_testBugBr4cp__6)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((UnitClause) (o_testBugBr4cp__6)).getActivity())), 0.1);
        Assert.assertEquals("1", ((UnitClause) (o_testBugBr4cp__6)).toString());
        Assert.assertEquals("", ((VecInt) (o_testBugBr4cp__8)).toString());
        Assert.assertTrue(((VecInt) (o_testBugBr4cp__8)).isEmpty());
        Assert.assertFalse(((OriginalBinaryClause) (o_testBugBr4cp__10)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testBugBr4cp__10)).getActivity())), 0.1);
        int[] array_891875899 = new int[]{4,6};
        	int[] array_1935558803 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testBugBr4cp__10).getLits();
        	for(int ii = 0; ii <array_891875899.length; ii++) {
        		org.junit.Assert.assertEquals(array_891875899[ii], array_1935558803[ii]);
        	};
        Assert.assertEquals("2[?] 3[?]", ((OriginalBinaryClause) (o_testBugBr4cp__10)).toString());
        Assert.assertEquals(5, ((int) (((OriginalBinaryClause) (o_testBugBr4cp__10)).hashCode())));
        Assert.assertEquals("", ((VecInt) (o_testBugBr4cp__12)).toString());
        Assert.assertTrue(((VecInt) (o_testBugBr4cp__12)).isEmpty());
        Assert.assertFalse(((OriginalBinaryClause) (o_testBugBr4cp__16)).isSatisfied());
        Assert.assertEquals(0.0, ((double) (((OriginalBinaryClause) (o_testBugBr4cp__16)).getActivity())), 0.1);
        int[] array_2132100624 = new int[]{5,7};
        	int[] array_2041933864 = (int[])((org.sat4j.minisat.constraints.cnf.OriginalBinaryClause)o_testBugBr4cp__16).getLits();
        	for(int ii = 0; ii <array_2132100624.length; ii++) {
        		org.junit.Assert.assertEquals(array_2132100624[ii], array_2041933864[ii]);
        	};
        Assert.assertEquals("-2[?] -3[?]", ((OriginalBinaryClause) (o_testBugBr4cp__16)).toString());
        Assert.assertEquals(6, ((int) (((OriginalBinaryClause) (o_testBugBr4cp__16)).hashCode())));
        Assert.assertEquals(1, ((int) (o_testBugBr4cp__21)));
        Assert.assertEquals(1, ((int) (o_testBugBr4cp__22)));
        Assert.assertTrue(o_testBugBr4cp__23);
        Assert.assertTrue(o_testBugBr4cp__25);
        Assert.assertTrue(o_testBugBr4cp__27);
        Assert.assertTrue(o_testBugBr4cp__30);
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__37)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__43)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__44)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__49)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__50)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__51)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__57)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__58)));
        Assert.assertEquals(3, ((int) (o_testBugBr4cp__59)));
    }
}

