var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":160,"id":8418,"methods":[{"el":53,"sc":2,"sl":50},{"el":67,"sc":2,"sl":55},{"el":74,"sc":2,"sl":69},{"el":116,"sc":2,"sl":111},{"el":132,"sc":2,"sl":128},{"el":138,"sc":2,"sl":134},{"el":145,"sc":2,"sl":140}],"name":"MetadataManagementProxyTest","sl":45}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_119":{"methods":[{"sl":69}],"name":"testGelAllReleases","pass":true,"statements":[{"sl":71},{"sl":72},{"sl":73}]},"test_122":{"methods":[{"sl":111}],"name":"testGelAllEvents","pass":true,"statements":[{"sl":113},{"sl":114},{"sl":115}]},"test_48":{"methods":[{"sl":55}],"name":"testRegisterRelease","pass":true,"statements":[{"sl":57},{"sl":58},{"sl":59},{"sl":61},{"sl":62},{"sl":63},{"sl":64},{"sl":65},{"sl":66}]},"test_60":{"methods":[{"sl":134}],"name":"testSendFiles","pass":true,"statements":[{"sl":136},{"sl":137}]},"test_76":{"methods":[{"sl":128}],"name":"testJsonInstances","pass":true,"statements":[{"sl":130},{"sl":131}]},"test_90":{"methods":[{"sl":140}],"name":"testRealtimeFeedbackClassification","pass":true,"statements":[{"sl":142},{"sl":143},{"sl":144}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [48], [], [48], [48], [48], [], [48], [48], [48], [48], [48], [48], [], [], [119], [], [119], [119], [119], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [122], [], [122], [122], [122], [], [], [], [], [], [], [], [], [], [], [], [], [76], [], [76], [76], [], [], [60], [], [60], [60], [], [], [90], [], [90], [90], [90], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
